### ISSUE TITLE
plasmoid not showing/installing

### ISSUE THREAD

**Issue by OlafHaag** [bxabi/bumblebee-indicator#1]
Hey! How do I install the plasmoid? I went through the "add new" and download process using kde plasma 5.8 on manjaro, but the plasmoid never shows up in the list of applets, so I can't add it anywhere.
I acknowledge that it could be just a problem with my system, since other applets, like the yahoo weather widget have the same problem.

**Comment by bxabi** [comment]
hi. Sorry I was not available recently. Is there any improvement in the meanwhile, or still multiple plasmoids have issues?

**Comment by julien-gargot** [comment]
Hi,
Same issue than @Vaquero84.
`Linux 4.8.13-1-ARCH x86_64`
`plasmashell 5.8.5`

**Comment by bxabi** [comment]
This error seems to be caused by the plasmoid installing system, and it is not specific to this plasmoid. Please confirm that other plasmoids install successfully to reopen the issue.
