### ISSUE TITLE
help setup indicator

### ISSUE THREAD

**Issue by batmanm0b1E** [bxabi/bumblebee-indicator#3]
Hi I followed directions  setting up bumblebee in fedoraa and added this widget but it gives me this how do i setup

https://imgur.com/a/wUyr6ht

**Comment by bxabi** [comment]
Hi, I got a similar report from PClinuxOS today, and made a a new release with the fix.
Can you post the result of the following command (in terminal): 
`find /usr -name nvidia-smi`

**Comment by bxabi** [comment]
A fix was published based on the other report.
