### ISSUE TITLE
FullRepresentation does not display anything

### ISSUE THREAD

**Issue by david-geiger** [bxabi/bumblebee-indicator#4]
Hi,

On mageia Cauldron bumblebee-indicator does not display anything, see the attached screenshot, while the following command does:
$ sh /usr/share/plasma/plasmoids/bumblebee-kde5-plasmoid/contents/ui/locate-nvidia-smi.sh -q

Mageia Cauldron
Plasma 5.15.2
Framework 5.55.0
Qt 5.12.1

Our spec file:
http://svnweb.mageia.org/packages/cauldron/plasma-applet-bumblebee-indicator/current/SPECS/plasma-applet-bumblebee-indicator.spec?revision=1373967&view=markup

Regards,
David
![bumblebee_indicator](https://user-images.githubusercontent.com/4344460/54187199-4c33b980-44ad-11e9-9aa2-ec73c438c465.png)

**Comment by bxabi** [comment]
Thanks for the report. I can actually reproduce the issue, so I will send out an update as the fix is ready.

**Comment by david-geiger** [comment]
Also as you have first started with release 0.32 is it possible to continue with this logic? e.g.: release 0.6.1 should have been 0.61

because 0.32 is higher as 0.6.1

**Comment by bxabi** [comment]
Yes sure, will check before release to be consistent (maybe 0.70 then).

**Comment by bxabi** [comment]
I published the fix. Clicking on the widget refreshes th full representation through the "expanded" property now.

**Comment by david-geiger** [comment]
Ok, now it works fine! thanks

Just still one issue : I have to rename the X-KDE-PluginInfo-Name to make it work like:

sed -i 's|X-KDE-PluginInfo-Name=com.bxabi.bumblebee-indicator|X-KDE-PluginInfo-Name=bumblebee-kde5-plasmoid|' plasmoid/metadata.desktop

**Comment by bxabi** [comment]
I'm not sure why the plugininfo-name should be changed. Where is that used?
https://techbase.kde.org/Projects/Plasma/PIG gives guidelines, as that it should be unique.

**Comment by david-geiger** [comment]
This plugininfo-name is important because it is installed in "/usr/share/plasma/plasmoids/plugininfo-name/" so the plugininfo-name should be the same as the name plasmoid directory where it is installed.

e.g: if plugininfo-name is "com.bxabi.bumblebee-indicator" so the plasmoid directory should be "/usr/share/plasma/plasmoids/com.bxabi.bumblebee-indicator/" and not "/usr/share/plasma/plasmoids/bumblebee-kde5-plasmoid/"

**Comment by david-geiger** [comment]
Also could you provides a new release tarball from 0.70 tag, please?

**Comment by bxabi** [comment]
Thanks the reminder, I made the release tag :)

**Comment by david-geiger** [comment]
I have finally done a better fix on Mageia Cauldron:

sed -i 's|bumblebee-kde5-plasmoid|com.bxabi.bumblebee-indicator|' CMakeLists.txt

to replace "plasma_install_package(plasmoid bumblebee-kde5-plasmoid)"

for "plasma_install_package(plasmoid com.bxabi.bumblebee-indicator)"
